'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Send } from 'lucide-react';
import { useSocket } from '@/hooks/use-socket';
import { useChatStore } from '@/store/chat-store';
import { SearchState } from '@/components/chat/search-state';
import { ReportModal } from '@/components/chat/report-modal';
import { BlockButton } from '@/components/chat/block-button';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
const userId = 'demo-user';
export default function TextChatPage() { const socket = useSocket(userId); const { queueState, match, messages, addMessage, setMatch, setQueueState } = useChatStore(); const [body, setBody] = useState(''); const [typing, setTyping] = useState(false); useEffect(() => { socket.on('match:found', setMatch); socket.on('chat:message', addMessage); socket.on('chat:typing', () => { setTyping(true); setTimeout(() => setTyping(false), 1200); }); return () => { socket.removeAllListeners(); }; }, [socket, setMatch, addMessage]); function join() { setQueueState('searching'); socket.emit('queue:join', { userId, socketId: socket.id, trustScore: 82, filters: { mode: 'TEXT', languages: ['en'], regions: [], interests: ['language'] } }); } function send(e: FormEvent) { e.preventDefault(); if (!body.trim() || !match) return; socket.emit('chat:message', { sessionId: match.sessionId, senderId: userId, body, sentAt: new Date().toISOString(), clientId: crypto.randomUUID() }); setBody(''); } return <main className="mx-auto flex min-h-screen max-w-5xl flex-col px-4 py-6"><div className="mb-4 flex items-center justify-between"><h1 className="text-3xl font-bold">Text chat</h1><div className="flex gap-2"><ReportModal sessionId={match?.sessionId} reportedId={match?.partnerId} /><BlockButton blockedId={match?.partnerId} /></div></div>{queueState !== 'matched' ? <div className="space-y-6"><SearchState mode="text" /><Button size="lg" onClick={join}>Start text chat</Button></div> : <><div className="flex-1 space-y-3 overflow-y-auto rounded-[2rem] border border-border bg-card p-4">{messages.map((m) => <div key={m.clientId} className={`max-w-[80%] rounded-3xl p-3 ${m.senderId===userId?'ml-auto bg-primary text-primary-foreground':'bg-secondary'}`}>{m.body}</div>)}{typing && <p className="text-sm text-muted-foreground">Stranger is typing…</p>}</div><form onSubmit={send} className="sticky bottom-0 mt-3 flex gap-2 bg-background py-3"><Input value={body} onChange={(e) => { setBody(e.target.value); socket.emit('chat:typing', { sessionId: match?.sessionId }); }} placeholder="Type a message. Avoid personal info." /><Button><Send className="size-4" />Send</Button></form></>}</main>; }
