'use client';
import { useEffect, useState } from 'react';
import { useSocket } from '@/hooks/use-socket';
import { useWebRTC } from '@/features/webrtc/use-webrtc';
import { useChatStore } from '@/store/chat-store';
import { SearchState } from '@/components/chat/search-state';
import { ReportModal } from '@/components/chat/report-modal';
import { BlockButton } from '@/components/chat/block-button';
import { WarningBanner } from '@/components/moderation/warning-banner';
import { ControlDock } from '@/components/video/control-dock';
import { VideoPanel } from '@/components/video/video-panel';
import { Button } from '@/components/ui/button';
const userId = 'demo-user';
export default function VideoChatPage() { const socket = useSocket(userId); const { queueState, match, setQueueState, setMatch } = useChatStore(); const [warning, setWarning] = useState(''); const rtc = useWebRTC(socket, match?.sessionId); useEffect(() => { socket.on('match:found', (m) => { setMatch(m); rtc.startCall(m.initiator); }); socket.on('call:offer', ({ offer }) => rtc.acceptOffer(offer)); socket.on('call:answer', ({ answer }) => rtc.acceptAnswer(answer)); socket.on('call:ice-candidate', ({ candidate }) => rtc.addIceCandidate(candidate)); socket.on('moderation:warning', (w) => setWarning(w.message)); socket.on('partner:disconnected', () => setQueueState('ended')); return () => { socket.removeAllListeners(); }; }, [socket, rtc, setMatch, setQueueState]); const join = async () => { setQueueState('searching'); await rtc.startLocalPreview(); socket.emit('queue:join', { userId, socketId: socket.id, trustScore: 82, filters: { mode: 'VIDEO', languages: ['en'], regions: [], interests: ['music'], safeModeTextFirst: true } }); }; return <main className="mx-auto max-w-7xl px-4 py-6 pb-28 md:pb-6"><div className="mb-4 flex items-center justify-between"><div><h1 className="text-3xl font-bold">Video chat</h1><p className="text-sm text-muted-foreground">Consent-first media, fast next, always-visible reporting.</p></div><div className="flex gap-2"><ReportModal sessionId={match?.sessionId} reportedId={match?.partnerId} /><BlockButton blockedId={match?.partnerId} /></div></div>{warning && <WarningBanner message={warning} />}{rtc.permissionError && <WarningBanner message={`${rtc.permissionError} Use text chat or allow permissions in your browser.`} />}{queueState !== 'matched' && <div className="space-y-6"><SearchState mode="video" /><Button size="lg" onClick={join}>Start searching</Button></div>}{queueState === 'matched' && <><div className="grid gap-4 lg:grid-cols-2"><VideoPanel stream={rtc.remoteStream} label="Stranger" /><VideoPanel stream={rtc.localStream} label="You" muted /></div><ControlDock onMic={rtc.toggleMic} onCamera={rtc.toggleCamera} onNext={() => socket.emit('session:next', { userId, sessionId: match?.sessionId })} onEnd={() => { rtc.cleanup(); socket.emit('session:end', { userId, sessionId: match?.sessionId }); setQueueState('ended'); }} /></>}</main>; }
